### PR TITLE
Changes to support Python 3

### PR DESCRIPTION
**Pull request by jshipley**
- use str instead of unicode for py3
- use dict.items instead of dict.iteritems for py3

### CODE REVIEW

**Comment by crazykilla15** [comment]
you can directly override the unicode variable on python 3, minimizing code changes

If it's python 3, unicode = str
if not, nothing.

**Comment by cheevahagadog** [comment]
Any update on when a Python 3 version will be available?

**Comment by dhamaniasad** [comment]
Hey @cheevahagadog!

I manage a fork of this project that has incorporated the Python 3 support already. I will work soon on merging my fork back into this repo. Until that is accomplished, I would recommend that you check out the fork in case you need Python 3 support right now.

**Comment by imndaiga** [comment]
I believe there's a requirements bug with flask-whooshalchemy (0.8) and your fork @dhamaniasad. Both require Flask==0.10.1 and Whoosh==2.6.0, much older packages than should be necessary IMO

**Pull request closed without merging**
