### PR TITLE
Compatibility with query results without pk field

### PR DESCRIPTION
**Pull request by zahariash**
BaseQuery.paginate() method works now.

### CODE REVIEW

**Comment by kedmenec** [comment]
agreed, this fixed the pagination for whoosh_searches for me.  Can someone merge it please.

**Comment by widnyana** [comment]
ping @gyllstromk

**Comment by dhamaniasad** [comment]
@ojle @kedmenec @widnyana I just merged this in my fork and have pushed this to PyPI [here](https://pypi.python.org/pypi/Flask-WhooshAlchemy-Redux).

**Comment by rlam3** [comment]
Should we be using whooshalchemy redux moving forward?

**Comment by dhamaniasad** [comment]
@rlam3 I do plan on incorporating at least bug fixes(and any changes to Flask-WhooshAlchemy) to Flask-WhooshAlchemy-Redux, and Flask-WhooshAlchemy seems abandoned, so Flask-WhooshAlchemy-Redux should be safe to use.

**Pull request closed without merging**
